Update formatting
datasciencecampus/transport-network-performance pull request #100
Opened 2023-08-23 13:04 UTC by CBROWN-ONS

## Description

Fixes #60 #61

## Motivation and Context

The motivation behind this PR is to address bugs introduced in the `_check_parent_dir_exists()` function
in src/transport_preformance/utils/defences.py. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

I have used unit tests to ensure that directories are being successfully created. This includes creating single parent directories and also multiple parent directories.  
Tests have also been completed to ensure that when `create=False` in `_check_parent_dir_exists()`, an error is thrown if the parent directory does not already exist.  
Further tests have been created to ensure that file paths including any number of '\' characters are processed correctly through converting to forward slash and then converting into an os specific path object.  
These tests were completed on both Windows and macOS.

Test configuration details:
Test 1:  
* OS: Windows 10
* Python version: 3.9.13
* Java version: N/A
* Python management system: Conda

Test 2:  
* OS: macOS Big Sur 11.6
* Python version: 3.9.13
* Java version: N/A
* Python management system: virtualenv

## Advice for reviewer

'macOS' tests were completed on my personal machine (off network, non work related).  
Also, github actions passed the tests on both Ubuntu and MacOS.
## Checklist:

- [x] My code follows the intended structure of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Additional comments

2023-08-23 19:18 UTC, CBROWN-ONS commented on src/transport_performance/utils/defence.py
> +    pth = pth.replace("\\", "/").replace(repr("\\"), "").replace("'", "")
This isn't ideal but it's the only way to ensure paths are consistent and also that paths including singular \ (escape char) are correctly processed. It also provides the leniency for the users path to include _n_ number of '\\' in a path.  
An example of this includes `out_pth="D:\\\dir1\dir2\\dir3\dir4\file.html"`

2023-08-24 09:01 UTC, CBROWN-ONS commented on src/transport_performance/utils/defence.py
> +    pth = str(pth).replace("\\", "/").replace(repr("\\"), "").replace("'", "")
This isn't ideal but it's the only way to ensure paths are consistent and also that paths including singular \ (escape char) are correctly processed. It also provides the leniency for the users path to include n number of '\' in a path.
An example of this includes out_pth="D:\\\dir1\dir2\\dir3\dir4\file.html"

2023-08-29 10:46 UTC, SergioRec requested changes
`makedirs` works as expected. Small issue in test for creation of subdirectories. Proposed alternative solution for backslashes issue.

2023-08-29 10:46 UTC, SergioRec commented on src/transport_performance/utils/defence.py
>  def _check_parent_dir_exists(pth, param_nm, create=False):
Added to technical debt #103 : this function needs documentation. Behaviour is not as I'd expect. It will get the parent directory of whatever path is fed into the function, so if called like this, it will not throw any error even though the directory does not exist:

```
path1 = os.path.join(here(), 'no_folder')
_check_parent_dir_exists(path1, 'n', create=False)
```

It will however throw an error if something else was appended to the path:
```
path2 = os.path.join(here(), 'no_folder//no_file.txt')
_check_parent_dir_exists(path2, 'n', create=False)
```

2023-08-29 10:46 UTC, SergioRec commented on src/transport_performance/utils/defence.py
> +    pth = str(pth).replace("\\", "/").replace(repr("\\"), "").replace("'", "")
When I pass your example path into the function, I get a wrong output. This is what's parsed using the `replace` line:

```
>>>path = "D:\\dir1\dir2\dir3\dir4\file.html"
>>>str(path).replace("\\", "/").replace(repr("\\"), "").replace("'", "")

'D:/dir1/dir2/dir3/dir4\x0cile.html'
```

So it seems it is escaping the "f" character ("\f" is a [FF character](https://stackoverflow.com/questions/44955635/how-to-print-ff-form-feed-character) which is printed as "\x0c"). This may be an issue in macOS only so you might not be able to reproduce in Windows.

2023-08-29 10:46 UTC, SergioRec commented on src/transport_performance/utils/defence.py
> +    pth = str(pth).replace("\\", "/").replace(repr("\\"), "").replace("'", "")
Discussed with @ethan-moss and suggested that we just do some logic for this check:
- If it's a Path object, use it as is.
- If it's a string, check that it only uses single forward slashes, if not throw an error requesting the correct format.

This could be added into the `_is_path_like` function.

2023-08-29 10:46 UTC, SergioRec commented on tests/utils/test_defence.py
> +        assert os.path.exists(
Tested this assertion by changing `makedirs` to `mkdir` so no subfolders were created. The test fails, but I get a `FileNotFoundError: [Errno 2] No such file or directory` instead of the `AssertionError`. I think this is because if no directories are created, the function will fail before getting to the assertion. So in this case perhaps testing for this specific error with a `with FileNotFoundError` context?

2023-08-30 08:17 UTC, SergioRec approved these changes
#60 and #61 are fixed now.

Issue #105 added as technical debt.

2023-08-30 08:19 UTC, merged