68 69 Tidy up docstrings in GTFS module
datasciencecampus/transport-network-performance pull request #158
Opened 2023-09-29 10:35 UTC by r-leyshon

## Description

Adds type hinting and standardises Returns and Raises sections of all modules in GTFS module.

Fixes #68 
Fixes #69 

## Motivation and Context

Standardise func and method signatures for sphinx docs build.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Test configuration details:
* OS: macos
* Python version: 3.9.13
* Java version: NA
* Python management system: pip

## Advice for reviewer

In completing this work, I have noticed that the module needs to be standardised with changes in utils.defence.py, in places ensuring that utility type defences are used and removing some examples of duplicated type checks. I will handle this in a separate issue #157

## Checklist:

- [X] My code follows the intended structure of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Additional comments

2023-10-02 08:08 UTC, CBROWN-ONS requested changes
### Summary
Great work getting all the docstrings and type hinting done!   
I have a few requested changes/concerns which I've decided to include here rather than comment on specific lines as it should be more clear here.  
### Changes/Concerns  
#### validation.py  
- The docstring for `GtfsInstance` has no 'Attributes' or 'Methods' section. Look [here](https://numpydoc.readthedocs.io/en/latest/format.html#documenting-classes) for an example 
- The `GtfsInstance` class has no docstring for the class constructor (not sure why pre-commit hasn't picked this up)
- On lines 296 and 364, type hinting for a `Union[x, y]` is used in the format (x, y). The general consensus seems to be to used Union[x, y] within the docstring as this is the object we have requested to be returned. [This](https://stackoverflow.com/questions/34647966/how-to-express-multiple-types-for-a-single-parameter-or-a-return-value-in-docstr) thread on stack overflows shows someone using this format. It is also present throughout other methods of `GtfsInstance`.
- On line 345 in the `viz_stops` method of `GtfsInstance`, there is no optional statement for optional parameters within the docstring.
- On line 370, there is no 'Default to' statement in the docstring
- The docstring for `_get_preprocessed_trips()` (line 370) has no 'Returns' section. (Lenient on this as it is a private function)

#### routes.py
- On the docstring for `_construst_extended_schema_table()` (starting at line 16), there are no 'optional' and 'Defaults to' included for the parameters. If we are being super picky we could also update type hinting to specify the return type (list, list).
- Missing docstring for `_get_response_text` (line 60). Happy not to include as it's a private function
- Missing optional statement/keyword for optional params in docstring for `scrape_route_type_loookup` (line 67)
	
#### gtfs_utils.py
- Missing 'optional' for parameters in docstring for `bbox_filter_gtfs()` (line 19)

2023-10-03 13:21 UTC, r-leyshon commented
Hey @CBROWN-ONS , just double checking this one:
> On the docstring for _construst_extended_schema_table() (starting at line 16), there are no 'optional' and 'Defaults to' included for the parameters. If we are being super picky we could also update type hinting to specify the return type (list, list).

I don't have any optional or default params for this func. Do you see the same func signature as me:

```
def _construct_extended_schema_table(
    some_soup: BeautifulSoup, cd_list: list, desc_list: list
) -> tuple:

```

2023-10-03 13:44 UTC, CBROWN-ONS commented
> Hey @CBROWN-ONS , just double checking this one:
> 
> > On the docstring for _construst_extended_schema_table() (starting at line 16), there are no 'optional' and 'Defaults to' included for the parameters. If we are being super picky we could also update type hinting to specify the return type (list, list).
> 
> I don't have any optional or default params for this func. Do you see the same func signature as me:
> 
> ```
> def _construct_extended_schema_table(
>     some_soup: BeautifulSoup, cd_list: list, desc_list: list
> ) -> tuple:
> ```
> 
> Other than this, I believe I've implemented everything bar the internal utility `_get_response_text `, which is so small it documents itself (just needed it to avoid complexity hook).

Great work clearing all of this up so quickly @r-leyshon . I've reviewed your changes and can confirm that all feedback has been acted upon.  
In regards to the above comment. This was a mistake on my end sorry. You are correct in stating that there are not any optional/'default to' params in this function.

2023-10-03 13:44 UTC, CBROWN-ONS approved these changes

2023-10-03 13:44 UTC, merged