164 166 170 Add source data folder and improve pathing to package root
datasciencecampus/transport-network-performance pull request #171
Opened 2023-10-06 11:52 UTC by CBROWN-ONS

## Description

This PR includes multiple improvements to the package,  including fixing bugs that stopped a user without the entire repo from using the functionality of this package.  

Summarised Changes:
- Added a data directory in `src/transport_performance`.
- Moved data files (non-code) that the package depends on into the data directory and removed them from their previous locations.
- Added a `MANIFEST.in` file to ensure the correct data files are being included in the package.
- Added a `constants.py` file that allows for easier use of constants in a centralised area.
- The `PKG_PTH` constant has been adopted across the package in areas where data files are used, ensuring the code still functions after installing only the package.
- `GtfsInstance()` now has an additional parameter `route_lookup_pth`. This allows for the user to specify their own route type lookup rather than forcing them to use the default one (currently saved in the data folder).
- Fixed an OSM test that was failing on windows. This was a small change and only required some changes to the formatting of paths in raised errors.

Fixes #166 
Fixes #170 
Fixes #164 
Fixes #122 

## Motivation and Context

The motivation of this PR is to ensure that the `transport_performance` package can be successfully installed through pip without leaving the user with missing data (that is required to use some of the main functions of the package).  
There are also updates that give the user more flexibility, such as the new parameter in `GtfsInstance()`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Test configuration details:
* OS: Windows 10
* Python version: 3.9.13
* Java version: N/A
* Python management system: Conda

## Advice for reviewer

To learn more about the use of the data folder and `MANIFEST.in`, read the first section of [this page](https://setuptools.pypa.io/en/latest/userguide/datafiles.html).

## Checklist:

- [x] My code follows the intended structure of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Additional comments

Issues raised as a result of this PR include:
#169

2023-10-09 10:00 UTC, r-leyshon requested changes
Hi @CBROWN-ONS , before I get into the line by line stuff, I've realised that it would be best to discuss one file structure change first:
I feel differently about newport-20230613_gtfs.zip than I do route_lookup.pkl. The GTFS is much larger thank the pickle, nearly a mb. 
The pickle is used in `gtfs.validation.GtfsInstance._plot_summary()` for a real-world use, here building a table used for presenting readable route type statistics in the GTFS validation HTML outputs. This file is therefore crucial to the functionality of the api.
The GTFS file; in contrast; was included with the intention as a test fixture only. The fact that default paths point at it would be for developer convenience reasons only. Packaging this fixture would be of almost no use to users of our API, unless they had a curious interest in the specific bounding box around Newport.
Rather than including it in the src folder, I would opt to remove default file paths pointing at the fixture and refactor the test suites. Hope that makes sense, happy to discuss with the broader team if necessary. In the same way that "tests/data/newport-2023-06-13.osm.pbf” is treated.
Files impacted by this suggested change:
* tests/gtfs/test_gtfs_utils.py
* tests/gtfs/test_routes.py
* tests/gtfs/test_validation.py
* tests/osm/test_osm_utils.py
* tests/utils/test_defence.py
* src/transport_performance/gtfs/validation.py
* src/transport_performance/gtfs/routes.py
* src/transport_performance/gtfs/gtfs_utils.py
* src/transport_performance/data/gtfs/newport-20230613_gtfs.zip
* .gitignore

2023-10-09 10:34 UTC, CBROWN-ONS commented
> Hi @CBROWN-ONS , before I get into the line by line stuff, I've realised that it would be best to discuss one file structure change first:
> 
> I feel differently about newport-20230613_gtfs.zip than I do route_lookup.pkl. The GTFS is much larger thank the pickle, nearly a mb. 
> 
> The pickle is used in `gtfs.validation.GtfsInstance._plot_summary()` for a real-world use, here building a table used for presenting readable route type statistics in the GTFS validation HTML outputs. This file is therefore crucial to the functionality of the api.
> 
> The GTFS file; in contrast; was included with the intention as a test fixture only. The fact that default paths point at it would be for developer convenience reasons only. Packaging this fixture would be of almost no use to users of our API, unless they had a curious interest in the specific bounding box around Newport.
> 
> Rather than including it in the src folder, I would opt to remove default file paths pointing at the fixture and refactor the test suites. Hope that makes sense, happy to discuss with the broader team if necessary. In the same way that "tests/data/newport-2023-06-13.osm.pbf” is treated.
> 
> Files impacted by this suggested change:
> 
> * tests/gtfs/test_gtfs_utils.py
> 
> * tests/gtfs/test_routes.py
> 
> * tests/gtfs/test_validation.py
> 
> * tests/osm/test_osm_utils.py
> 
> * tests/utils/test_defence.py
> 
> * src/transport_performance/gtfs/validation.py
> 
> * src/transport_performance/gtfs/routes.py
> 
> * src/transport_performance/gtfs/gtfs_utils.py
> 
> * src/transport_performance/data/gtfs/newport-20230613_gtfs.zip
> 
> * .gitignore

Hi Rich. Me and Ethan had previously discussed this but had waited on implementing it before discussing it with the rest of the team. I 100% agree that we should remove default file paths to the Newport test fixture. I do think it might be more useful to raise as a feature request for now however as it would be a breaking change (I believe).

2023-10-09 10:40 UTC, r-leyshon commented
One other point to note, failing test on --runsetup flag:
```
tests/test_setup.py::TestSetup::test_r5py_setup FAILED                                                                [  0%]
```
Line 43 is searching in the test fixtures dir `  search_pth = os.path.join("tests", "data")`

2023-10-09 10:41 UTC, r-leyshon commented on pyproject.toml
> +include-package-data = true
agreed that [setuptools docs](https://setuptools.pypa.io/en/stable/userguide/datafiles.html) suggest this is on as default.

2023-10-09 10:46 UTC, CBROWN-ONS commented
> One other point to note, failing test on --runsetup flag:
> 
> ```
> 
> tests/test_setup.py::TestSetup::test_r5py_setup FAILED                                                                [  0%]
> 
> ```
> 
> Line 43 is searching in the test fixtures dir `  search_pth = os.path.join("tests", "data")`

This should be resolved once the test fixtures are moved back to the tests folder and default file paths for Newport fixtures are removed from the Gtfs module

2023-10-10 11:37 UTC, CBROWN-ONS commented
HI @r-leyshon. I've just had a look over the changes and tested them locally (pytest + external test of `GtfsInstance()`). Everything is working as expected, and from reading through the code it seems like we have met what we set out to achieve with making the `gtfs_pth` parameter required.  
Happy for this to be merged if you are!

2023-10-10 12:11 UTC, r-leyshon approved these changes

2023-10-10 12:11 UTC, merged