186 filter to date method in gtfsinstance
datasciencecampus/transport-network-performance pull request #190
Opened 2023-10-23 10:34 UTC by r-leyshon

## Description

bbox_filter_gtfs optionally filters to a list of dates present within the gtfs calendar.

Fixes #186 

## Motivation and Context

Reducing GTFS archives to valid features (stops, shapes etc) on a given date appears to reduce the likelihood of encountering r5py errors when building transport network. It is currently thought that these errors are encountered due to specific fast travel issues, although further investigation and reproduction of the encountered error is ongoing.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

bbox_filter_gtfs will continue to work as before, although specifying a populated list will run the `gtfs_kit.feed.restrict_to_date()` logic.

## How Has This Been Tested?

Defensive checks and test suite included. Also a test marked with runinteg to ensure the r5py trasport network can be built from the filtered GTFS file.

Test configuration details:
* OS: macos
* Python version: Python 3.9.13
* Java version: openjdk 11.0.19 2023-04-18 LTS
* Python management system: pip

## Advice for reviewer

## Checklist:

- [X] My code follows the intended structure of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Additional comments

2023-10-31 13:11 UTC, CBROWN-ONS requested changes
Hi @r-leyshon . Great work on this. Everything is working as expected.  
I have a few small comments however they aren't huge things to clear up.  

On the r5py stuff, from eyeballing it, it looks good to me. We might however want to get someone else to quickly run the test on their machine to ensure it works.

2023-10-31 13:11 UTC, cbrowning04 commented on src/transport_performance/gtfs/gtfs_utils.py
> +
Is it possible to include type hinting + type defences here. A possible (optional) implementation might be:  
```python
def _validate_datestring(date_text: str, form: str="%Y%m%d") -> None:
    _type_defence(date_text, "date_text", str)
    _type_defence(form, "form", str)
    try:
        datetime.strptime(date_text, form)
    except ValueError:
        raise ValueError(
            f"Incorrect date format, {date_text} should be {form}"
        )
    return None
```

2023-10-31 13:11 UTC, cbrowning04 commented on src/transport_performance/gtfs/gtfs_utils.py
> +
After further consideration, I would also suggest adding some sort of docstring for this function. I appreciate that it is a private function, however even only a description of the function would be useful.

2023-10-31 13:11 UTC, cbrowning04 commented on src/transport_performance/gtfs/gtfs_utils.py
> +
Another comment on this function, sorry!  
I believe that this function could be useful in other modules, not just GTFS. I would support moving this function to a file such as defence.py.

2023-10-31 13:11 UTC, cbrowning04 commented on src/transport_performance/gtfs/gtfs_utils.py
> +        date filter will be applied.
Most likely a 'won't change' but I'd like your opinion on this.  
Do you think we should alter this docstring to match other dosctrings in the form of having 'defaults to' as the last part of a param description (without the 'meaning that no
date filter will be applied.' afterwards)

2023-10-31 13:11 UTC, cbrowning04 commented on src/transport_performance/gtfs/gtfs_utils.py
>  def bbox_filter_gtfs(
Do we want to allow the user to pass a date format to this function? This would be helpful for the user and a good QOL update.

To allow for comparisons with the GTFS date format (%Y%m%d) we could convert to this format within the function if it isn't the passed format.

2023-11-06 10:08 UTC, r-leyshon commented
> Hi @r-leyshon . Great work on this. Everything is working as expected. I have a few small comments however they aren't huge things to clear up.
> 
> On the r5py stuff, from eyeballing it, it looks good to me. We might however want to get someone else to quickly run the test on their machine to ensure it works.

@SergioRec @ethan-moss can anyone help complete the review by running the tests locally on their machine?

2023-11-06 11:20 UTC, r-leyshon commented on src/transport_performance/gtfs/gtfs_utils.py
>  def bbox_filter_gtfs(
This should be the current implementation - `_validate_datestring()` would be compatible with any valid C-format date code, whereas `bbox_filter_gtfs()` uses the internal with the required date format expected by `gtfs_kit`.

2023-11-06 11:22 UTC, r-leyshon commented
@CBROWN-ONS I have implemented all your suggestions except the final comment, which unless I have misunderstood is already the case. Many thanks for the good catches once again. Did you feel you needed a more in depth review of the tests or does a passing CI suite do enough to demonstrate the behaviour is as expected?

2023-11-06 11:46 UTC, CBROWN-ONS commented
> @CBROWN-ONS I have implemented all your suggestions except the final comment, which unless I have misunderstood is already the case. Many thanks for the good catches once again. Did you feel you needed a more in depth review of the tests or does a passing CI suite do enough to demonstrate the behaviour is as expected?

Hi Rich. After reviewing your comments on the matter, I agree that we are fine not to accept a parameter for date format while filtering the GTFS.

Great work on the other changes. Regarding the r5py stuff, I'm happy to merge as the CI demonstrates that these tests pass and are operational. Let me know if you agree with this, and I will merge this into dev.

2023-11-06 12:09 UTC, r-leyshon commented
> > @CBROWN-ONS I have implemented all your suggestions except the final comment, which unless I have misunderstood is already the case. Many thanks for the good catches once again. Did you feel you needed a more in depth review of the tests or does a passing CI suite do enough to demonstrate the behaviour is as expected?
> 
> Hi Rich. After reviewing your comments on the matter, I agree that we are fine not to accept a parameter for date format while filtering the GTFS.
> 
> Great work on the other changes. Regarding the r5py stuff, I'm happy to merge as the CI demonstrates that these tests pass and are operational. Let me know if you agree with this, and I will merge this into dev.

Good to go from my end, thanks again.

2023-11-06 12:35 UTC, CBROWN-ONS approved these changes

2023-11-06 12:56 UTC, merged